export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const GET_TASKS = 'GET_TASKS'
export const TASKS_ERROR = 'TASKS_ERROR'
export const REMOVE_TASKS = 'REMOVE_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const TASK_SELECTED = 'TASK_SELECTED'
export const TASK_UPDATED = 'TASK_UPDATED'

